import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { load, MINI_BUNDLE, tempDir } from "./fixtures/kit.mjs";
import { buildGpx, buildSeedSql } from "./exports.mjs";
import { ll } from "./geo.mjs";
import { buildLayers } from "./layers.mjs";
import { publishDir } from "./publish.mjs";

const layers = (targets = "all") => buildLayers(load(MINI_BUNDLE).bundle, { interrowTol: 0.0125, targets }).files;
const matches = (text, re) => [...text.matchAll(re)].map((m) => m[1]);

test("route.gpx has waypoints only for routed targets, in route order, and the route as its track", () => {
  const files = layers();
  const gpx = buildGpx(files["targets.geojson"], files["route.geojson"]);
  assert.match(gpx, /^<\?xml version="1.0" encoding="UTF-8"\?>\n<gpx version="1.1" creator="Solemtrix"/);
  assert.deepEqual(matches(gpx, /<name>(\d+\. T\d+)<\/name>/g), ["1. T001", "2. T002"]);
  assert.deepEqual(matches(gpx, /<desc>([^<]*)<\/desc>/g), ["gap V01-R002", "missing V02-R001"]);
  const [lon, lat] = ll([629560, 5220280]);
  assert.match(gpx, new RegExp(`<wpt lat="${lat}" lon="${lon}">`));
  const route = files["route.geojson"].features[0];
  assert.equal(matches(gpx, /<trkpt lat="([^"]+)"/g).length, route.geometry.coordinates.length);
  assert.match(gpx, /<trkpt lat="47.1230335" lon="28.7073776"\/>/, "starts at START");
  assert.match(gpx, new RegExp(`<trk><name>Ruta de inspecție \\(${Math.round(route.properties.length_m * 100) / 100} m\\)</name>`));
  assert.match(gpx, /<\/trkseg><\/trk>\n<\/gpx>\n$/);
});

test("route.gpx escapes XML and is the same with --targets route", () => {
  const files = layers();
  const odd = { ...files["targets.geojson"], features: [{ ...files["targets.geojson"].features[0],
    properties: { ...files["targets.geojson"].features[0].properties, target_id: "T<1>&" } }] };
  assert.match(buildGpx(odd, files["route.geojson"]), /<name>1\. T&lt;1&gt;&amp;<\/name>/);
  const routeOnly = layers("route");
  assert.equal(buildGpx(routeOnly["targets.geojson"], routeOnly["route.geojson"]), buildGpx(files["targets.geojson"], files["route.geojson"]));
});

test("seed SQL upserts public.survey with /data/<id> and the footprint, quoting safely", () => {
  const footprint = { type: "Polygon", coordinates: [[[28.70, 47.12], [28.71, 47.12], [28.71, 47.13], [28.70, 47.12]]] };
  const sql = buildSeedSql({ id: "siret3", name: "Sireț3 d'test", captured_at: "2025-05-20", source: "3DATA", license: "CC BY 4.0" }, footprint);
  assert.match(sql, /^-- generated by src\/Web\/frontend\/scripts\/build-survey\.mjs --emit-seed/);
  assert.match(sql, /values \('siret3', 'Sireț3 d''test', '2025-05-20', '3DATA', 'CC BY 4\.0', '\/data\/siret3', extensions\.st_multi\(/);
  assert.ok(sql.includes(JSON.stringify(footprint)));
  assert.match(sql, /on conflict \(id\) do update set name = excluded\.name, .*footprint = excluded\.footprint;\n$/);
});

test("publishDir replaces the survey folder as a whole and leaves no temporary folder", (t) => {
  const root = tempDir(t);
  publishDir(root, "s1", { "a.json": { json: { v: 1 } }, "stale.txt": { text: "old" } });
  const dir = publishDir(root, "s1", { "a.json": { json: { v: 2 } }, "m.csv": { copy: path.join(MINI_BUNDLE, "measurements.csv") } });
  assert.deepEqual(fs.readdirSync(dir).sort(), ["a.json", "m.csv"]);
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir, "a.json"), "utf8")), { v: 2 });
  assert.deepEqual(fs.readdirSync(root), ["s1"]);
});

test("publishDir keeps the previous folder when writing fails", (t) => {
  const root = tempDir(t);
  publishDir(root, "s1", { "a.json": { json: { v: 1 } } });
  assert.throws(() => publishDir(root, "s1", { "a.json": { json: { v: 2 } }, "b.csv": { copy: path.join(root, "missing.csv") } }), /writing .*s1\.tmp failed/);
  assert.deepEqual(fs.readdirSync(root), ["s1"]);
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root, "s1", "a.json"), "utf8")), { v: 1 });
});
