// Download files of a survey: route.gpx, the verbatim bundle copies (route in EPSG:32635, measurements.csv)
// and the optional Supabase seed that registers the survey (modelled on scripts/gen-seed-sql.mjs output).
import { r2 } from "./geo.mjs";

// published file name → bundle file, copied byte for byte
export const VERBATIM = { "route_EPSG32635.geojson": "route.geojson", "measurements.csv": "measurements.csv" };

const XML_ENTITIES = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" };
const xml = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => XML_ENTITIES[c]);

/** GPX 1.1 (same template as build-data.mjs): a waypoint per routed target in route order, the route as the track. */
export const buildGpx = (targets, route) => {
  const routed = targets.features
    .filter((f) => f.properties.route_order !== null && f.properties.route_order !== undefined)
    .sort((a, b) => a.properties.route_order - b.properties.route_order);
  const line = route.features[0];
  const wpt = (f) => {
    const [lon, lat] = f.geometry.coordinates;
    const p = f.properties;
    return `  <wpt lat="${lat}" lon="${lon}"><name>${xml(`${p.route_order}. ${p.target_id}`)}</name><desc>${xml(`${p.type} ${p.row_id ?? ""}`)}</desc></wpt>\n`;
  };
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Solemtrix" xmlns="http://www.topografix.com/GPX/1/1">\n` +
    routed.map(wpt).join("") +
    `  <trk><name>Ruta de inspecție (${r2(line.properties.length_m)} m)</name><trkseg>\n` +
    line.geometry.coordinates.map(([lon, lat]) => `    <trkpt lat="${lat}" lon="${lon}"/>\n`).join("") +
    `  </trkseg></trk>\n</gpx>\n`
  );
};

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const geom = (g) => `extensions.st_multi(extensions.st_setsrid(extensions.st_geomfromgeojson(${q(JSON.stringify(g))}), 4326))`;

/** Idempotent upsert of public.survey; footprint = the organizer study area (4326), like the siret3-mock seed. */
export const buildSeedSql = (survey, footprint) =>
  [
    "-- generated by src/Web/frontend/scripts/build-survey.mjs --emit-seed — do not edit by hand",
    "",
    `insert into public.survey (id, name, captured_at, source, license, data_path, footprint) values (${q(survey.id)}, ${q(survey.name)}, ${q(survey.captured_at)}, ${q(survey.source)}, ${q(survey.license)}, ${q(`/data/${survey.id}`)}, ${geom(footprint)})`,
    `  on conflict (id) do update set name = excluded.name, captured_at = excluded.captured_at, source = excluded.source, license = excluded.license, data_path = excluded.data_path, footprint = excluded.footprint;`,
    "",
  ].join("\n");
